// Collection of insightful SEO and marketing quotes for the loading screen
// Sourced from loadingmessages.md

export const loadingQuotes = [
  "Google is a language model, not a search engine. It ranks thoughts, not just websites.",  
  "The first three search results get almost 70% of clicks. If you're not there, you're invisible.",  
  "The highest-ranking websites aren't the best, they just know how to game Google.",  
  "A site with 1,000 fake backlinks can outrank a site with 10 real ones. Google hates it but still falls for it.",  
  "Updating an old blog post can make it outrank a brand-new one.",  
  "Google tracks how long people stay on your page. If they leave too fast, your ranking drops.",  
  "TikTok is stealing searches from Google. Young people search TikTok first because they trust real people more.",  
  "The best way to boost rankings is to get people to search your name directly.",  
  "If your website takes longer than three seconds to load, half your visitors leave.",  
  "The top results on Google are at least three years old. Freshness matters less than you think.",  
  "People don't read sales pages. They skim. Make your point fast.",  
  "Your first sentence should punch them in the face. No one reads past a boring opening.",  
  "The best sales copy makes people feel like they discovered it on their own.",  
  "Every sales objection is about trust. Too expensive means they don't trust it's worth it.",  
  "The real secret to pricing is introducing an expensive version first. It makes the second price feel cheap.",  
  "People buy to escape something. The bigger the pain, the easier the sale.",  
  "The easiest people to sell to are the ones who bought something similar and hated it.",  
  "Social proof only works if it's specific. \"10,000 happy customers\" means nothing. A real name and a dollar amount mean everything.",  
  "Selling high-ticket isn't about value, it's about removing effort. Rich people pay to do nothing.",  
  "Curiosity wins. \"How I made $10,000\" is okay. \"The weirdest way I made $10,000\" is unskippable.",  
  "The most-read part of any sales letter is the P.S. If they skim everything, they still read that.",  
  "A single word change can double your sales. \"Buy now\" vs. \"Claim your spot\" triggers different emotions.",  
  "If your copy doesn't make people feel something, it's dead.",  
  "Every viral idea has one thing in common. It's impossible to ignore.",  
  "A confused brain says no. The more you explain, the worse you do.",  
  "Scarcity makes people act. If they think they can wait, they will.",  
  "People don't buy products. They buy who they will become.",  
  "The best way to make someone want something is to make them feel like it's not for them.",  
  "The worst thing you can do in sales is beg. Act like they need to qualify to buy.",  
  "The best testimonials don't talk about the product. They talk about the transformation.",  
  "Make your price feel smaller. Instead of saying $3,600 a year, say $10 a day.",  
  "If your sales page isn't converting, it's probably too logical. People buy on emotion.",  
  "Bullet points work better than paragraphs. The brain loves bite-sized info.",  
  "Never call it a discount. Call it a special offer. Discounts sound cheap.",  
  "Urgency beats logic every time. A weak offer with a deadline will outsell a strong one with no rush.",  
  "Your copy should pass the \"So what?\" test. If the reader can say \"so what?\" after a sentence, delete it.",  
  "Your biggest competition isn't another company. It's the customer doing nothing.",  
  "People don't believe what you say. They believe what others say about you.",  
  "If you want to sell more, remove risk. A guarantee can double conversions.",  
  "The best CTA isn't \"Buy now.\" It's \"Here's what happens next.\" People fear the unknown.",  
  "The hardest product to sell is a \"maybe.\" If they aren't a \"hell yes\" right away, they're a no.",  
  "Writing at a ninth-grade level makes people trust you more. Big words kill sales.",  
  "If your offer isn't obvious in five seconds, you've lost them.",  
  "People remember stories, not facts. If you aren't telling a story, they won't remember you.",  
  "Every good sales letter is a horror story. Here's what happens if you don't act.",  
  "If you aren't making money, you're not selling enough. If you're not selling enough, your offer sucks.",  
  "Make it feel like their idea. \"Try this\" is weak. \"Here's what's working for people like you\" is strong.",  
  "The best way to double your price is to make people feel like they're getting in on something exclusive.",  
  "People trust screenshots more than text. If you show proof, show it like they'd see it in real life.",  
  "The most persuasive word in copy is \"you.\"",  
  "People don't like to think. The simpler your offer, the better it sells.",  
  "The best subject lines don't describe the email. They create curiosity.",  
  "Free trials work because people get attached. Once they have it, they don't want to lose it.",  
  "The strongest headline is the one that makes people say, \"Wait… what?\"",  
  "People will pay more to fix a problem than to improve something.",  
  "If a product is too cheap, people assume it's worthless.",  
  "People love things that feel stolen. \"This formula was leaked from a $10,000 mastermind\" is a goldmine.",  
  "The first three words of a headline determine if people keep reading.",  
  "80% of people read headlines. Only 20% read the rest.",  
  "If you wouldn't say it in a conversation, don't write it in your copy.",  
  "People buy when they see themselves in the offer. The copy should feel like it was written just for them.",  
  "Adding \"Why?\" at the end of a sentence makes people curious. \"Most people fail at this. Why?\"",  
  "If they don't feel a problem, they won't buy the solution.",  
  "People don't want a drill. They want a hole in the wall. Sell the hole.",  
  "The best way to get someone to buy is to make them feel like they've already decided.",  
  "The longer they think about it, the less likely they are to buy.",  
  "\"Because\" is a magic word. \"You need this\" is weak. \"You need this because it fixes X\" is strong.",  
  "Your copy should sound like one person talking to one person. Not a company talking to a crowd.",  
  "People are more afraid of losing money than excited to make money.",  
  "The secret to pricing is contrast. $99 feels cheap next to $499.",  
  "If they aren't buying, they don't believe you.",  
  "Everything sells better with a deadline.",  
  "If you want people to act fast, tell them someone else is about to take their spot.",  
  "People will pay more for faster results.",  
  "Testimonials should talk about the buyer, not just the product.",  
  "A higher price makes people take it more seriously.",  
  "People buy from people they like. If they don't like you, your copy won't matter.",  
  "Every great offer has a built-in reason why it's available now and not later.",  
  "People like hearing about the mistakes others made so they can avoid them.",  
  "A deal that feels too good to be true will be ignored.",  
  "\"What's in it for me?\" is the only question your copy needs to answer.",  
  "People don't want more choices. They want one clear answer.",  
  "The most persuasive stories have a struggle, a solution, and proof it works.",  
  "People need to feel safe before they buy. If they feel pressured, they'll back out.",  
  "The best way to sell something is to describe what happens if they don't buy.",  
  "People trust weirdly specific numbers more than round ones. \"Made $9,247\" is stronger than \"Made $10,000.\"",  
  "The best-selling products solve problems people know they have.",  
  "People will scroll forever if each sentence makes them want to read the next one.",  
  "The best copywriting trick is to delete half of what you wrote.",  
  "People don't buy what's new. They buy what feels familiar.",  
  "A single idea, clearly explained, beats a long sales pitch every time."
]; 